// Subset of Database types for the MCP server edge function.
// Source: src/integrations/supabase/types.ts (auto-generated by Supabase).
// Keep in sync when schema changes.

export interface Database {
  public: {
    Tables: {
      ingredients: {
        Row: {
          id: string;
          name: string;
          calories_per_serving: number;
          protein_per_serving: number;
          fat_per_serving: number;
          carbs_per_serving: number;
          fiber_per_serving: number;
          sodium_per_serving: number;
          brand: string | null;
          category: string | null;
          serving_description: string | null;
          serving_grams: number;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['ingredients']['Row']> & { name: string; user_id: string };
        Update: Partial<Database['public']['Tables']['ingredients']['Row']>;
      };
      recipes: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          image: string | null;
          category: string | null;
          instructions: string | null;
          link: string | null;
          notes: string | null;
          servings: number;
          total_calories: number;
          total_protein: number;
          total_fat: number;
          total_carbs: number;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['recipes']['Row']> & { name: string; user_id: string };
        Update: Partial<Database['public']['Tables']['recipes']['Row']>;
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          ingredient_id: string;
          name: string;
          serving_multiplier: number;
        };
        Insert: Partial<Database['public']['Tables']['recipe_ingredients']['Row']> & { recipe_id: string; ingredient_id: string; name: string };
        Update: Partial<Database['public']['Tables']['recipe_ingredients']['Row']>;
      };
      recipe_tags: {
        Row: {
          id: string;
          recipe_id: string;
          tag_name: string;
          user_id: string;
        };
        Insert: Partial<Database['public']['Tables']['recipe_tags']['Row']> & { recipe_id: string; tag_name: string; user_id: string };
        Update: Partial<Database['public']['Tables']['recipe_tags']['Row']>;
      };
      meals: {
        Row: {
          id: string;
          name: string;
          source_recipe_id: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['meals']['Row']> & { name: string; user_id: string };
        Update: Partial<Database['public']['Tables']['meals']['Row']>;
      };
      meal_ingredients: {
        Row: {
          id: string;
          meal_id: string;
          ingredient_id: string;
          name: string;
          serving_multiplier: number;
        };
        Insert: Partial<Database['public']['Tables']['meal_ingredients']['Row']> & { meal_id: string; ingredient_id: string; name: string };
        Update: Partial<Database['public']['Tables']['meal_ingredients']['Row']>;
      };
      meal_plans: {
        Row: {
          id: string;
          user_id: string;
          week_start_date: string;
          day_of_week: string;
          meal_slot: string;
          meal_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['meal_plans']['Row']> & { user_id: string; day_of_week: string; meal_slot: string; meal_id: string };
        Update: Partial<Database['public']['Tables']['meal_plans']['Row']>;
      };
      weekly_targets: {
        Row: {
          id: string;
          user_id: string;
          week_start_date: string;
          tdee: number;
          strategy: string;
          daily_calories: number;
          protein: number;
          fat: number;
          carbs: number;
          preset_id: string | null;
          weight_kg: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['weekly_targets']['Row']> & { user_id: string };
        Update: Partial<Database['public']['Tables']['weekly_targets']['Row']>;
      };
      mcp_api_keys: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          key_hash: string;
          key_prefix: string;
          expires_at: string | null;
          revoked_at: string | null;
          last_used_at: string | null;
          created_at: string;
        };
        Insert: Partial<Database['public']['Tables']['mcp_api_keys']['Row']> & { user_id: string; key_hash: string; key_prefix: string };
        Update: Partial<Database['public']['Tables']['mcp_api_keys']['Row']>;
      };
      diet_presets: {
        Row: {
          id: string;
          name: string;
          tdee_multiplier: number;
          protein_per_kg: number | null;
          carbs_per_kg: number | null;
          fat_per_kg: number | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['diet_presets']['Row']> & { name: string; user_id: string };
        Update: Partial<Database['public']['Tables']['diet_presets']['Row']>;
      };
    };
  };
}

/** Macro-relevant ingredient fields */
export interface IngredientMacros {
  calories_per_serving: number;
  protein_per_serving: number;
  fat_per_serving: number;
  carbs_per_serving: number;
}

/** Input shape for create_ingredient tool */
export interface CreateIngredientInput {
  name: string;
  calories_per_serving: number;
  protein_per_serving: number;
  fat_per_serving: number;
  carbs_per_serving: number;
  fiber_per_serving?: number;
  sodium_per_serving?: number;
  brand?: string;
  category?: string;
  serving_description?: string;
  serving_grams?: number;
}
