import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

declare const __BUILD_ID__: string;

const isInIframe = (() => {
  try {
    return window.self !== window.top;
  } catch {
    return true;
  }
})();

const isPreviewHost =
  window.location.hostname.includes("id-preview--") ||
  window.location.hostname.includes("lovableproject.com") ||
  window.location.hostname.includes("lovable.app") === false &&
    window.location.hostname.includes("lovable");

const shouldRegisterSW = !isInIframe && !isPreviewHost;

async function registerOrCleanupSW() {
  if (!("serviceWorker" in navigator)) return;

  if (!shouldRegisterSW) {
    // In preview/iframe: aggressively kill any SW and caches so dev iteration is clean
    const regs = await navigator.serviceWorker.getRegistrations();
    await Promise.all(regs.map((r) => r.unregister()));
    if ("caches" in window) {
      const keys = await caches.keys();
      await Promise.all(keys.map((k) => caches.delete(k)));
    }
    return;
  }

  // Production: register the SW generated by vite-plugin-pwa
  try {
    const { registerSW } = await import("virtual:pwa-register");
    registerSW({ immediate: true });
  } catch {
    // SW module unavailable — fail silently
  }
}

async function checkForUpdate() {
  try {
    const res = await fetch("/?_cb=" + Date.now(), {
      cache: "no-store",
      headers: { Accept: "text/html" },
    });
    if (!res.ok) return false;
    const html = await res.text();
    const match = html.match(
      /<meta\s+name="wholefuel-build-id"\s+content="([^"]+)"/
    );
    if (match && match[1] !== __BUILD_ID__) {
      const url = new URL(window.location.href);
      if (!url.searchParams.has("_updated")) {
        url.searchParams.set("_updated", match[1]);
        window.location.replace(url.toString());
        return true; // reloading
      }
    }
  } catch {
    // network error — continue
  }
  return false;
}

async function boot() {
  const reloading = await checkForUpdate();
  if (reloading) return;

  // Strip the _updated marker if present
  const url = new URL(window.location.href);
  if (url.searchParams.has("_updated")) {
    url.searchParams.delete("_updated");
    window.history.replaceState(null, "", url.pathname + url.search + url.hash);
  }

  // Fire and forget — don't block render
  registerOrCleanupSW();

  createRoot(document.getElementById("root")!).render(<App />);
}

boot();
